# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=35)),
                ('date_time', models.DateTimeField()),
                ('mode', models.CharField(choices=[('call', 'call'), ('whatsapp', 'whatsapp'), ('email', 'email')], max_length=15)),
                ('interaction', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=25)),
                ('order_id', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('sku', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('shipping_cost', models.FloatField()),
                ('dispatch_date', models.DateField()),
                ('delivery_vendor', models.CharField(max_length=25)),
                ('tracking_id', models.CharField(max_length=35)),
                ('delivery_date', models.DateField()),
                ('note', models.TextField(max_length=300)),
                ('review', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('10-15', '10-15'), ('15-18', '15-18'), ('18-20', '18-20'), ('20-25', '20-25'), ('25-30', '25-30'), ('30-35', '30-35'), ('35-40', '35-40'), ('40-45', '40-45'), ('45-50', '45-50'), ('50-55', '50-55')], max_length=7)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=7)),
                ('income_level', models.CharField(choices=[('affluent', 'affluent'), ('UpperMiddle', 'UpperMiddle'), ('LowerMiddle', 'LowerMiddle')], max_length=20)),
                ('occupation', models.CharField(choices=[('student', 'student'), ('Working', 'Working'), ('Housewife', 'Housewife'), ('Other', 'Other')], max_length=15)),
                ('occupation_details', models.TextField(max_length=1000)),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried'), ('divorced', ' divorced')], max_length=12)),
                ('spouse', models.TextField(max_length=300)),
                ('children', models.TextField(max_length=300)),
                ('rating', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
                ('places_lived', models.ManyToManyField(to='Consumer_Analytics.City')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('alt_name', models.CharField(blank=True, max_length=40)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('pincode', models.IntegerField(blank=True)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tag', models.ManyToManyField(blank=True, to='Consumer_Analytics.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('alt_text', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='Consumer_Analytics.User')),
            ],
        ),
        migrations.AddField(
            model_name='sociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.User'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.User'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to='Consumer_Analytics.User'),
        ),
    ]
