# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-01 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0003_auto_20170101_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone2',
        ),
    ]
