# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0006_auto_20170101_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=254, null=True)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='places_lived',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('pp', 'Prepaid'), ('cod', 'Cash on Delivery'), ('c', 'cash')], default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='children',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone1',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spouse',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='alternateaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_address', to='Consumer_Analytics.User'),
        ),
    ]
