# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-01 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0007_auto_20170101_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Consumer', 'verbose_name_plural': 'Consumers'},
        ),
    ]
