# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0009_user_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sku',
        ),
        migrations.AddField(
            model_name='sku',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ordered', to='Consumer_Analytics.Order'),
        ),
    ]
