# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-03 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0013_auto_20170103_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternateaddress',
            options={'verbose_name': 'AlternateAddress', 'verbose_name_plural': 'Alternate Addresses'},
        ),
        migrations.AlterModelOptions(
            name='userimage',
            options={'verbose_name': 'User Image', 'verbose_name_plural': 'User Images'},
        ),
    ]
