# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-03 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0014_auto_20170103_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='places_lived',
            field=models.ManyToManyField(blank=True, to='Consumer_Analytics.City'),
        ),
    ]
