# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-03 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0016_auto_20170103_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='children',
            new_name='spouse_and_children',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='spouse',
            new_name='user_persona',
        ),
    ]
