# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0019_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, help_text='Date Of Birth', null=True),
        ),
    ]
