# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0020_auto_20170103_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
