# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0021_auto_20170103_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_vendor',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatch_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='review',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
