# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0022_auto_20170104_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True),
        ),
    ]
