# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0023_auto_20170105_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateaddress',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
