# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0024_auto_20170105_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by', to='Consumer_Analytics.User'),
            preserve_default=False,
        ),
    ]
