# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0026_remove_sku_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
