# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-07 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0027_auto_20170107_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
