# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-03-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0030_ordercount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ordercount',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='dcount',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
