# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-03-11 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0031_auto_20170312_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dcount',
        ),
    ]
