# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-03-11 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0032_remove_order_dcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercount',
            name='order_count',
        ),
    ]
