# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-03-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0033_remove_ordercount_order_count'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ordercount',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='ordercount',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ordercount',
            name='dcount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
