# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-03-11 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0034_auto_20170312_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercount',
            old_name='user',
            new_name='user_name',
        ),
    ]
