# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-03-11 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0035_auto_20170312_0324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCount',
        ),
    ]
