# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-03-12 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0037_ordercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCount',
        ),
    ]
