# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0038_delete_ordercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.User', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstaComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='InstaPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.InstaAlbum')),
            ],
        ),
        migrations.AddField(
            model_name='instacomments',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.InstaPic'),
        ),
    ]
