# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0039_auto_20171214_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instacomments',
            name='comment',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='instapic',
            name='img',
            field=models.ImageField(null=True, upload_to='insta/'),
        ),
    ]
