# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0040_auto_20171214_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaalbum',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.User'),
        ),
    ]
