# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0041_auto_20171214_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaalbum',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
