# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0042_instaalbum_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instapic',
            old_name='user',
            new_name='album',
        ),
    ]
