# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0045_auto_20171214_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapic',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
