# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0046_instapic_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapic',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instapic',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
