# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-16 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0047_auto_20171214_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instapic',
            name='tags',
        ),
    ]
