# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-12-18 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0048_remove_instapic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('link', models.URLField(verbose_name='Profile Link')),
                ('profile_pic', models.ImageField(null=True, upload_to='fb/', verbose_name='Profile Picture')),
            ],
        ),
    ]
