# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-12-18 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0049_fbprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500, null=True)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FbFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, null=True)),
                ('label', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FbProfileLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FbWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500, null=True)),
                ('text', models.TextField(max_length=500, null=True)),
                ('additional', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fbprofile',
            options={'verbose_name': 'Facebook Profile', 'verbose_name_plural': 'Facebook Profiles'},
        ),
        migrations.AddField(
            model_name='fbprofile',
            name='current_city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Current City'),
        ),
        migrations.AddField(
            model_name='fbprofile',
            name='hometown',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Home Town'),
        ),
        migrations.AlterField(
            model_name='fbprofile',
            name='link',
            field=models.URLField(unique=True, verbose_name='Profile Link'),
        ),
        migrations.AddField(
            model_name='fbwork',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.FbProfile'),
        ),
        migrations.AddField(
            model_name='fbprofilelink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.FbProfile'),
        ),
        migrations.AddField(
            model_name='fbfavourite',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.FbProfile'),
        ),
        migrations.AddField(
            model_name='fbeducation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consumer_Analytics.FbProfile'),
        ),
    ]
