# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-12-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0051_fbprofile_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbeducation',
            name='additional',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
