# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Analytics', '0053_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Prospect', 'Prospect')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='instaalbum',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Prospect', 'Prospect')], max_length=9, null=True),
        ),
    ]
