# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-03 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=35)),
                ('date_time', models.DateTimeField()),
                ('mode', models.CharField(choices=[('call', 'call'), ('whatsapp', 'whatsapp'), ('email', 'email')], max_length=15)),
                ('interaction', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=25)),
                ('order_id', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('method', models.CharField(choices=[('pp', 'Prepaid'), ('cod', 'Cash on Delivery'), ('c', 'cash')], default=None, max_length=25)),
                ('shipping_cost', models.FloatField()),
                ('dispatch_date', models.DateField()),
                ('delivery_vendor', models.CharField(max_length=25)),
                ('tracking_id', models.CharField(max_length=35)),
                ('delivery_date', models.DateField()),
                ('note', models.TextField(max_length=300)),
                ('review', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=40)),
                ('owner_phone', models.CharField(max_length=13, unique=True)),
                ('alt_name', models.CharField(max_length=40)),
                ('alt_phone1', models.CharField(blank=True, max_length=13)),
                ('alt_phone2', models.CharField(blank=True, max_length=13)),
                ('website', models.URLField(blank=True)),
                ('email1', models.EmailField(blank=True, max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('pincode', models.IntegerField(blank=True)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('rating', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C')], max_length=3)),
                ('app_installed', models.BooleanField()),
                ('video_tutorial', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ordered', to='Salon_Analytics.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('alt_text', models.CharField(max_length=10)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_image', to='Salon_Analytics.Salon')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon_Analytics.Salon'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_log', to='Salon_Analytics.Salon'),
        ),
    ]
