# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-03 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon_Analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Salon', 'verbose_name_plural': 'Salons'},
        ),
    ]
