# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon_Analytics', '0002_auto_20170103_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='salon_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
