# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-01-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon_Analytics', '0005_auto_20170104_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='alt_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
