# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-12-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon_Analytics', '0008_auto_20170107_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='salon_type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Prospect', 'Prospect')], max_length=9, null=True),
        ),
    ]
